apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claims
resources:
  - namespace.yaml
  - api.yaml
  - frontend.yaml
images:
  - name: claims-api
    newName: claims-api
    newTag: local
  - name: claims-frontend
    newName: claims-frontend
    newTag: local
